name: Keep Render App Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping Home
        run: |
          curl -s https://student-predictor-hiw5.onrender.com > /dev/null
          curl -s https://student-predictor-hiw5.onrender.com/predictdata > /dev/null
